language: cpp
dist: trusty
script: bash judge.sh
before_install:
- sudo apt-get install -y libcgal-dev
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - boost1.67
